Master
artioki/ReactTs pull request #1
Opened 2022-05-30 10:21 UTC by artioki

2022-05-30 10:23 UTC, artioki commented
Тестовое задание - интерфейс для сайта. 
https://github.com/web-bee-ru/ru-test-assignments/blob/main/react/01-news-list.md

2022-07-25 21:37 UTC, crutch12 commented
Опа, я забыл про этот PR совсем

2022-07-25 21:38 UTC, crutch12 commented
отдал @stilwuc

2022-07-27 08:55 UTC, Stilwuc commented
@artioki Можешь на codesandbox выложить плз?
лень пулить и собирать)

2022-07-27 10:55 UTC, artioki commented
@Stilwuc вот https://codesandbox.io/s/dazzling-forest-7nq0pf?file=/src/components/Header.tsx
Но я давно уже делал, понимаю что многое надо почистить. Сегодня вечером постараюсь закончить

2022-07-28 08:39 UTC, Stilwuc commented
> @Stilwuc вот https://codesandbox.io/s/dazzling-forest-7nq0pf?file=/src/components/Header.tsx Но я давно уже делал, понимаю что многое надо почистить. Сегодня вечером постараюсь закончить

Ок, тогда давай как сам поправишь напиши
Я после этого и заскочу)

2022-07-28 21:57 UTC, artioki commented
@Stilwuc заскакивай. Надеюсь ты в этих переплетениях не заблудишься. Не нравится мне это redux)

2022-07-29 10:14 UTC, Stilwuc requested changes

2022-07-29 10:14 UTC, Stilwuc commented on my-app/src/components/ItemNews.tsx
> +  & .foot{
этот селектор можно в Footer styled превратить

2022-07-29 10:14 UTC, Stilwuc commented on my-app/src/components/ItemNews.tsx
> +    ??
А зачем тут это?)

2022-07-29 10:14 UTC, Stilwuc commented on my-app/src/types/TypeReducer.ts
> +import { IFeedItem } from './IFeedItem';
Префиксы интерфейсов через `I` не стоит)

2022-07-29 10:14 UTC, Stilwuc commented on my-app/src/store/actionCreater/fetchFeed.ts
> +/* eslint-disable no-console */
лучше убить

2022-07-29 10:14 UTC, Stilwuc commented on my-app/src/components/ItemComment.tsx
> +  strStrong:string;
Не, ну норм названия же хочется)
А то str, str2 и тд такое себе, надо семантически описать значение пропа а не синтаксически

2022-07-29 10:14 UTC, Stilwuc commented on my-app/src/components/ItemComment.tsx
> +  hides?:boolean|undefined;
У тебя уже short undefined стоит `?`, и ты после этого явно его еще раз пишешь

2022-07-29 10:14 UTC, Stilwuc commented on my-app/src/components/ItemComment.tsx
> +  Item: IFeedItem;
Странный кейс пропа

2022-07-29 10:15 UTC, Stilwuc commented
Нормас нормас, пару вещей поправить и будет 👍

2022-07-29 21:57 UTC, artioki commented on my-app/src/components/ButtonReload.tsx
> +  }, [funcSet, second]);
Косяч еще внутри был. Shallowequal не сравнивает объекты с вложенностью нормально. Но вроде починил. Правда при старте все равно два раза useEffect срабатывает. Но это чтоб наверняка

2022-07-29 23:14 UTC, artioki commented
@Stilwuc codesandbox- https://codesandbox.io/s/keen-mclean-d7q41n
Поправил все, кроме иконок. Видимо codesandbox с ними не очень дружит. А так, вот скрин как у меня на локальной сети выглядит.
![image](https://user-images.githubusercontent.com/100927254/181859351-dc00af4d-76b1-4738-9be4-175693497a34.png)
![image](https://user-images.githubusercontent.com/100927254/181859375-b7b60c7e-8030-4cb1-8e92-9b05c253f29a.png)

2022-08-01 10:58 UTC, Stilwuc approved these changes
Пару комментов не поправил (с codeStyle и форматированием), но ок, не критичные вещи.
Можешь мержить так, если конечно не хочешь поправить форматирование ;)

2022-08-02 12:45 UTC, artioki commented
@crutch12 готово

2022-08-03 00:01 UTC, crutch12 approved these changes
Засчитано, можно мержить

2022-08-08 22:15 UTC, merged